<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="fichas">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="ficha" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string"/>
                            <xs:element name="iniciales">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[A-Z][A-Z][A-Z]"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="edad" type="xs:integer"/>
                            <xs:element name="iniciales-al-reves" type="xs:string">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[A-Za-z][A-Za-z][A-Za-z]"/>
                                        <!--Esta expresión regular [A-Za-z][A-Za-z][A-Za-z] indica que cada
                                        letra puede ser una mayúscula (A-Z) o una minúscula (a-z),
                                        permitiendo así que las tres letras puedan ser mayúsculas o
                                        minúsculas indistintamente en "iniciales" e "iniciales-al-reves"-->
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>
